config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "callbacks" }

  root "home#home"

  match "monster_attributes/:id" => "monsters#update_attributes", :via => :put, :as => :update_attributes

  resources :inventories, only: :create
  resource :slot_machines, only: [:show, :update]
  resources :items, only: :index

  resources :users do
    resources :monsters, except: :index
  end

  get '*path' => redirect('/')

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/monster.rb
class Monster < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  before_update :average_happiness

  scope :least_happy, -> { order(happiness: :asc) }

  def give_item_to_monster(params)
    inventory = Inventory.find_by_id(params[:monster][:inventory_id])
    case inventory.item.item_type
    when "food"
      self.update_properties({ 'hunger': inventory.item.effectiveness, 'boredom': -(rand(1..3)) })
    when "medicine"
      self.update_properties({ 'health': inventory.item.effectiveness, 'hunger': -(rand(1..3)) })
    when "toy"
      self.update_properties({ 'boredom': inventory.item.effectiveness, 'hunger': -(rand(1..3)) })
    when "other"
      self.update_properties({ 'hunger': inventory.item.effectiveness, 'boredom': 0 })
      self.update_properties({ 'health': inventory.item.effectiveness, 'boredom': 0 })
      self.update_properties({ 'boredom': inventory.item.effectiveness, 'boredom': 0 })
    else
      nil
    end
    inventory.quantity -= 1
    inventory.save
    return true
  end

  def update_properties(hash)
    self.update(hash.keys[0].to_s => (self.attributes[hash.keys[0].to_s] + hash.values[0]).clamp(0, 5), hash.keys[1].to_s => (self.attributes[hash.keys[1].to_s] + hash.values[1]).clamp(0, 5))
  end

  def happy?
    case self.happiness
    when 5
      "Great!"
    when 4
      "Alright"
    when 3
      "OK."
    else
      "not so well..."
    end
  end

  def monster_age
    self.age = (((Time.now - self.created_at.localtime) / 1.hour) / 24).round
    self.age = self.age.clamp(1, 100)
    self.save
  end

  private

  def average_happiness
    self.happiness = (self.health + self.hunger + self.boredom) / 3
  end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :authenticate_user!

  def new
    @monster = current_user.monsters.new
  end

  def create
    @monster = current_user.monsters.create(monster_params)
    if @monster.save
      redirect_to root_path
    else
      flash.now[:name_error] = "#{@monster.errors.full_messages[0]}"
      render "new"
    end
  end

  def show
    @monster = current_user.monsters.find_by_id(params[:id])
    @monster.monster_age
  end

  def destroy
    @monster = current_user.monsters.find_by_id(params[:id])
    @monster.destroy
    redirect_to root_path
  end

  def edit
    @monster = current_user.monsters.find_by_id(params[:id])
  end

  def update
    @monster = current_user.monsters.find_by_id(params[:id])
    if @monster.update(monster_params)
      redirect_to user_monster_path(@monster)
    else
      flash.now[:message] = "#{@monster.errors.full_messages[0]}"
      render "edit"
    end
  end

  def update_attributes
    @monster = current_user.monsters.find_by_id(params[:id])
    item = @monster.give_item_to_monster(params)
    if item != nil
      redirect_to user_monster_path(@monster)
    else
      render "show"
    end
  end

  

  private

  def monster_params
    params.require(:monster).permit(:name, :age, :health, :happiness, :hunger, :boredom, :color)
  end

end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/monsters/_monster_attributes.html.erb
<div class="card">
  <div class="card-body">
    <h4 class="card-title">Age - <%= @monster.age %></h4>
    <p class="card-text">
      Health:&nbsp;
      <% @monster.health.times do %>
        <%= image_tag("heart.png", size: "20x20") %>&nbsp;
      <% end %><br>
      <br>
      Hunger:&nbsp;
      <% @monster.hunger.times do %>
        <%= image_tag("heart.png", size: "20x20") %>&nbsp;
      <% end %><br>
      <br>
      Boredom:&nbsp;
      <% @monster.boredom.times do %>
        <%= image_tag("heart.png", size: "20x20") %>&nbsp;
      <% end %>
    </p>
  </div>
</div>

app/views/monsters/_monster_form.html.erb
<%= form_for [current_user, @monster], class: "form-group" do |f| %>
  <%= f.label :name, "Name:" %>
  <%= f.text_field :name, { class: "form-control" } %>
  <%= f.label :color, "Color:" %>
  <%= f.select(:color, [["Blue", 1], ["Green", 2], ["Red", 3], ["White", 4]], {}, { class: "form-control" }) %>
  <%= f.hidden_field :age %>
  <%= f.hidden_field :health %>
  <%= f.hidden_field :happiness %>
  <%= f.hidden_field :hunger %>
  <%= f.hidden_field :boredom %>
  <br>
  <div class="text-right"><%= f.submit submit_text, class: "btn btn-primary" %></div>
<% end %>

app/views/monsters/_monster_items.html.erb
<div class="card">
  <div class="card-body">
    <h4 class="card-title text-right">Items</h4>
    <div class="w-30 d-inline-block">
      <% if current_user.inventories.all?{ |a| a.quantity == 0 } %>
        <h4>NO ITEMS</h4>
      <% else %>
        <% current_user.inventories.each do |i| %>
          <% if i.quantity > 0 %>
            <%= form_for :monster, url: update_attributes_path(@monster), method: :put do |f| %>
              <%= f.hidden_field :monster_id, :value => @monster.id %>
              <%= f.hidden_field :item_id, :value => i.item.id %>
              <%= f.hidden_field :inventory_id, :value => i.id %>
              <%= f.submit "#{i.item.name.capitalize} - #{i.quantity}", class: "btn btn-primary btn-sm mb-1" %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/monsters/_monster_main_card.html.erb
<div class="card">
  <div class="card-body">
    <h4 class="card-title text-center"><%= @monster.name.upcase %></h4>
    <div class="d-flex justify-content-center">
      <div class="monster_img" id="monster<%= @monster.color %>"></div>
    </div>
    <div class="d-flex justify-content-center">
      Happiness: &nbsp;
      <% @monster.happiness.times do %>
        <%= image_tag("heart.png", size: "20x20") %>&nbsp;
      <% end %>
    </div>
  </div>
</div>

app/views/monsters/edit.html.erb
<%= render partial: "layouts/error", locals: {variable: :message} %>
<div class="container">
  <div class="card">
    <div class="card-header">
      Edit Monster
    </div>
    <div class="card-body">
      <h4 class="card-title">Edit your Monster!</h4>
      <p class="card-text">
        <%= render partial: 'monsters/monster_form', locals: {submit_text: "Edit Monster"}%>
      </div>
    </div>
  </div>

app/views/monsters/new.html.erb
<%= render partial: "layouts/error", locals: {variable: :name_error} %>
<div class="container">
  <div class="card">
    <div class="card-header">
      New Monster
    </div>
    <div class="card-body">
      <h4 class="card-title">Create a New Monster!</h4>
      <p class="card-text">
        <%= render partial: 'monsters/monster_form', locals: {submit_text: "Create Monster"}%>
      </div>
    </div>
  </div>

app/views/monsters/show.html.erb
<div class="card-deck">
  <%= render 'monsters/monster_main_card' %>
  <%= render 'monsters/monster_attributes' %>
  <%= render 'monsters/monster_items' %>
</div>
<div class="d-flex justify-content-center">
  <%= form_for @monster, url: user_monster_path(@monster), method: :delete do |f| %>
    <%= f.submit "Delete Monster", class: "btn btn-primary", style: "margin: 20px 10px 30px 10px;" %>
  <% end %>
  <%= link_to "Edit Monster", edit_user_monster_path(@monster), class: "btn btn-primary", style: "margin: 20px 10px 30px 10px;"  %>
</div>
<%= stylesheet_link_tag "monsters" %>