config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "callbacks" }

  root "home#home"

  match "monster_attributes/:id" => "monsters#update_attributes", :via => :put, :as => :update_attributes

  resources :inventories, only: :create
  resource :slot_machines, only: [:show, :update]
  resources :items, only: :index

  resources :users do
    resources :monsters, except: :index
  end

  get '*path' => redirect('/')

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :monsters
  has_many :inventories
  has_many :items, through: :inventories

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :secure_validatable, :omniauthable, email_validation: false

  validates :username, presence: true

  def self.from_omniauth(auth) ## A custom class constructor I'm building myself
    ## check and see if a user with this provider (github) and uid exists; if not, create it
    where(provider: auth.provider, uid: auth.id).first_or_create do |user|
      user.provider = auth.provider ## so I know this user has authenticated with github previously
      user.username = auth.info.name
      user.uid = auth.id  ## so I know this user has authenticated with github previously, and I don't make a duplicate user
      user.email = auth.info.email
      user.password = Devise.friendly_token(20) ## dummy password to store in my app db
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def show
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_monster_view.html.erb
<% if !current_user.monsters.empty? %>
  <div class="row justify-content-center">
    <div class="card" style="max-width: 31rem;">
      <h3 class="card-header text-center">Your Monsters</h3>
      <div class="card-body" style="max-width: 495px;">
        <% current_user.monsters.least_happy.each do |m| %>
          <div class="w-30 d-inline-block">
            <a href="<%=user_monster_path(current_user, m)%>" class="btn btn-sq btn-primary" style="margin-bottom: 10px">
              <div class="align-content-center" style="margin-top: 20px;">
                <%= m.name %><br>
                <span style="font-size: 1px;">Feeling&nbsp;<%= m.happy? %></span>
              </div>
            </a>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <br>
  <h2 class="row justify-content-center">MAKE A MONSTER!</h2>
<% end %>

app/views/users/show.html.erb
<%= render partial: "layouts/error", locals: {variable: :message} %>
<h2 class="row justify-content-center">Welcome, <%= current_user.username.titleize %></h2>
<h3 class="row justify-content-center">Rupees: <%= current_user.rupees %>&#8377;</h3>
<%= render 'monster_view' %>
<BR>
<div class="row justify-content-center">
  <%= link_to "New Monster", new_user_monster_path(current_user), class: "btn btn-primary", style: "margin: 0 10px;"%>
  <%= link_to "Go to the Store", items_path, class: "btn btn-secondary", style: "margin: 0 10px;" %>
  <%= link_to "Gamble!", slot_machines_path, class: "btn btn-primary", style: "margin: 0 10px;" %>
</div>